# Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [44]:
arr = []
def atv(input_vector, col, increasing=False):
    
    if not increasing:
        output = np.array([x**(col-1-i) for x in input_vector for i in range(col)]).reshape(input_vector.size,col)
    elif increasing:
        output = np.array([x**i for x in input_vector for i in range(col)]).reshape(input_vector.size,col)
    
    return output

a = int(input("Size of array:"))
for i in range(a):
    arr.append(int(input("Element:")))
input_vector = np.array(arr)
print(input_vector)
col = int(input("Enter the number of columns: "))
print(col)
print(f'Output Matrix: \n{atv(input_vector,col,False)}')



Size of array:5
Element:1
Element:2
Element:3
Element:4
Element:5
[1 2 3 4 5]
Enter the number of columns: 3
3
Output Matrix: 
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


# Problem Statement
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [52]:
import numpy as np
try:
    def mov_avg(a,k):
        try:
            sum_a = np.cumsum(a)
            sum_a[k:] = sum_a[k:] - sum_a[:-k]
            return(sum_a[k-1:]/k)
        except:
            print("Error")
        
    a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
    k=3
    n = len(a)#Size of array
    print(f'Size of array is :{n}')
    ans = mov_avg(a,k).round(1)
    print(ans)
except Exception as e:
    print(e)

Size of array is :13
[  5.    4.7   5.7   6.7   9.7  28.7  49.3  72.7  84.   93.3 116.3]
